In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv(r'C:\Users\anasm\OneDrive\Documents\Projects\MediMindAI\datasets\training.csv')
df.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.shape

(4920, 18)

In [9]:
df.isnull().sum()

Disease          0
Symptom_1        0
Symptom_2        0
Symptom_3        0
Symptom_4      348
Symptom_5     1206
Symptom_6     1986
Symptom_7     2652
Symptom_8     2976
Symptom_9     3228
Symptom_10    3408
Symptom_11    3726
Symptom_12    4176
Symptom_13    4416
Symptom_14    4614
Symptom_15    4680
Symptom_16    4728
Symptom_17    4848
dtype: int64

In [62]:
columns = df.columns
column = columns.drop('Disease')
symptoms = []
for i in column:
    values = df[i].unique()
    for val in values:
        if val not in symptoms and pd.notnull(val):
            symptoms.append(val.strip().replace('_', ' '))

print(symptoms)

['itching', 'skin rash', 'continuous sneezing', 'shivering', 'stomach pain', 'acidity', 'vomiting', 'indigestion', 'muscle wasting', 'patches in throat', 'fatigue', 'weight loss', 'sunken eyes', 'cough', 'headache', 'chest pain', 'back pain', 'weakness in limbs', 'chills', 'joint pain', 'yellowish skin', 'constipation', 'pain during bowel movements', 'breathlessness', 'cramps', 'weight gain', 'mood swings', 'neck pain', 'muscle weakness', 'stiff neck', 'pus filled pimples', 'burning micturition', 'bladder discomfort', 'high fever', 'skin rash', 'nodal skin eruptions', 'shivering', 'chills', 'acidity', 'ulcers on tongue', 'vomiting', 'yellowish skin', 'stomach pain', 'loss of appetite', 'indigestion', 'patches in throat', 'high fever', 'weight loss', 'restlessness', 'sunken eyes', 'dehydration', 'cough', 'chest pain', 'dizziness', 'headache', 'weakness in limbs', 'neck pain', 'weakness of one body side', 'fatigue', 'joint pain', 'lethargy', 'nausea', 'abdominal pain', 'pain during bowel movements', 'pain in anal region', 'breathlessness', 'sweating', 'cramps', 'bruising', 'weight gain', 'cold hands and feets', 'mood swings', 'anxiety', 'knee pain', 'stiff neck', 'swelling joints', 'pus filled pimples', 'blackheads', 'bladder discomfort', 'foul smell of urine', 'skin peeling', 'blister', 'nodal skin eruptions', 'dischromic  patches', 'chills', 'watering from eyes', 'ulcers on tongue', 'vomiting', 'yellowish skin', 'nausea', 'stomach pain', 'burning micturition', 'abdominal pain', 'loss of appetite', 'high fever', 'extra marital contacts', 'restlessness', 'lethargy', 'dehydration', 'diarrhoea', 'breathlessness', 'dizziness', 'loss of balance', 'headache', 'blurred and distorted vision', 'neck pain', 'weakness of one body side', 'altered sensorium', 'fatigue', 'weight loss', 'sweating', 'joint pain', 'dark urine', 'swelling of stomach', 'cough', 'pain in anal region', 'bloody stool', 'chest pain', 'bruising', 'obesity', 'cold hands and feets', 'mood swings', 'anxiety', 'knee pain', 'hip joint pain', 'swelling joints', 'movement stiffness', 'spinning movements', 'blackheads', 'scurring', 'foul smell of urine', 'continuous feel of urine', 'skin peeling', 'silver like dusting', 'blister', 'red sore around nose', 'dischromic  patches', 'watering from eyes', 'vomiting', 'cough', 'nausea', 'loss of appetite', 'burning micturition', 'spotting  urination', 'passage of gases', 'abdominal pain', 'extra marital contacts', 'lethargy', 'irregular sugar level', 'diarrhoea', 'breathlessness', 'family history', 'loss of balance', 'lack of concentration', 'blurred and distorted vision', 'excessive hunger', 'dizziness', 'altered sensorium', 'weight loss', 'high fever', 'sweating', 'headache', 'fatigue', 'dark urine', 'yellowish skin', 'yellowing of eyes', 'swelling of stomach', 'distention of abdomen', 'bloody stool', 'irritation in anus', 'chest pain', 'obesity', 'swollen legs', 'mood swings', 'restlessness', 'hip joint pain', 'swelling joints', 'movement stiffness', 'painful walking', 'spinning movements', 'scurring', 'continuous feel of urine', 'silver like dusting', 'small dents in nails', 'red sore around nose', 'yellow crust ooze', 'cough', 'chest pain', 'loss of appetite', 'abdominal pain', 'spotting  urination', 'internal itching', 'passage of gases', 'irregular sugar level', 'blurred and distorted vision', 'family history', 'mucoid sputum', 'lack of concentration', 'excessive hunger', 'stiff neck', 'loss of balance', 'high fever', 'yellowish skin', 'headache', 'nausea', 'fatigue', 'dark urine', 'yellowing of eyes', 'distention of abdomen', 'history of alcohol consumption', 'breathlessness', 'sweating', 'irritation in anus', 'swollen legs', 'swollen blood vessels', 'lethargy', 'dizziness', 'diarrhoea', 'swelling joints', 'painful walking', 'unsteadiness', 'small dents in nails', 'inflammatory nails', 'yellow crust ooze', 'chest pain', 'abdominal pain', 'yellowing of eyes', 'internal itching', 'blurred and distorted vision', 'obesity', 'mucoid sputum', 'stiff neck', 'depression', 'yellowish skin', 'dark urine', 'nausea', 'diarrhoea', 'headache', 'loss of appetite', 'high fever', 'constipation', 'family history', 'history of alcohol consumption', 'fluid overload', 'breathlessness', 'swelled lymph nodes', 'sweating', 'malaise', 'swollen blood vessels', 'prominent veins on calf', 'dizziness', 'puffy face and eyes', 'fast heart rate', 'painful walking', 'unsteadiness', 'inflammatory nails', 'yellowing of eyes', 'obesity', 'excessive hunger', 'depression', 'irritability', 'dark urine', 'abdominal pain', 'muscle pain', 'diarrhoea', 'loss of appetite', 'mild fever', 'headache', 'nausea', 'constipation', 'yellow urine', 'fluid overload', 'breathlessness', 'sweating', 'swelled lymph nodes', 'malaise', 'phlegm', 'prominent veins on calf', 'puffy face and eyes', 'enlarged thyroid', 'fast heart rate', 'blurred and distorted vision', 'excessive hunger', 'increased appetite', 'irritability', 'visual disturbances', 'abdominal pain', 'muscle pain', 'mild fever', 'swelled lymph nodes', 'nausea', 'loss of appetite', 'diarrhoea', 'yellow urine', 'yellowing of eyes', 'sweating', 'malaise', 'phlegm', 'chest pain', 'enlarged thyroid', 'brittle nails', 'muscle weakness', 'drying and tingling lips', 'increased appetite', 'polyuria', 'visual disturbances', 'swelled lymph nodes', 'malaise', 'loss of appetite', 'pain behind the eyes', 'toxic look (typhos)', 'diarrhoea', 'mild fever', 'yellowing of eyes', 'abdominal pain', 'phlegm', 'throat irritation', 'fast heart rate', 'chest pain', 'brittle nails', 'swollen extremeties', 'muscle weakness', 'irritability', 'slurred speech', 'drying and tingling lips', 'polyuria', 'malaise', 'red spots over body', 'pain behind the eyes', 'back pain', 'belly pain', 'toxic look (typhos)', 'yellowing of eyes', 'muscle pain', 'receiving blood transfusion', 'acute liver failure', 'mild fever', 'throat irritation', 'redness of eyes', 'rusty sputum', 'fast heart rate', 'swollen extremeties', 'depression', 'irritability', 'abnormal menstruation', 'slurred speech', 'red spots over body', 'back pain', 'malaise', 'belly pain', 'muscle pain', 'receiving blood transfusion', 'receiving unsterile injections', 'coma', 'acute liver failure', 'yellowing of eyes', 'swelled lymph nodes', 'redness of eyes', 'sinus pressure', 'rusty sputum', 'depression', 'irritability', 'abnormal menstruation', 'palpitations', 'muscle pain', 'malaise', 'receiving unsterile injections', 'stomach bleeding', 'coma', 'swelled lymph nodes', 'sinus pressure', 'runny nose', 'irritability', 'abnormal menstruation', 'palpitations', 'red spots over body', 'muscle pain', 'stomach bleeding', 'malaise', 'phlegm', 'runny nose', 'congestion', 'abnormal menstruation', 'red spots over body', 'phlegm', 'chest pain', 'congestion', 'chest pain', 'blood in sputum', 'loss of smell', 'blood in sputum', 'loss of smell', 'muscle pain', 'muscle pain']

In [72]:
dataset = pd.DataFrame(0,index = df.index, columns=symptoms)
dataset

,itching,skin rash,continuous sneezing,shivering,stomach pain,acidity,vomiting,indigestion,muscle wasting,patches in throat,...,phlegm,chest pain,congestion,chest pain,blood in sputum,loss of smell,blood in sputum,loss of smell,muscle pain,muscle pain
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4916,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4918,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4919,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [74]:
for i in range(len(df)):
    for j in column:
        if pd.notnull(df[j][i]):
            dataset.at[i, df[j][i].strip().replace('_', ' ')] = 1
dataset['Disease'] = df['Disease']
dataset.head()

,itching,skin rash,continuous sneezing,shivering,stomach pain,acidity,vomiting,indigestion,muscle wasting,patches in throat,...,chest pain,congestion,chest pain,blood in sputum,loss of smell,blood in sputum,loss of smell,muscle pain,muscle pain,Disease
0,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection